install:
    - npm install -g doctest
    - npm install -g bower 
    - bower install jasmine jasmine.async sinonjs
    - bower install https://github.com/jcarver989/phantom-jasmine.git
    - bower install
# command to run tests
script: 
    # run unittests
    - node bower_components/phantom-jasmine/bin/phantom-jasmine tests/TestRunner.html
    # run doctests
    - doctest acmlib.js
notifications:
    irc: "irc.cat.pdx.edu#acm-dev"
